# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!


target 'HostingApp' do
  pod "Mixpanel"
end

target 'Keyboard' do
  pod "Mixpanel/AppExtension"
end

target 'KeyboardFramework' do

end
